import 'server-only';
import { cache } from 'react';
import manifest from '@/.generated/public-content.json';
import type { PublicManifest } from './schema';
// Generated by content:check before dev/build/typecheck. No runtime filesystem loader,
// directory tracing, preview roots, fixture switches, or draft data in the application graph.
export const getPublicManifest = cache(
  async (): Promise<PublicManifest> => manifest as PublicManifest,
);
